import { EUserRoleName } from "src/modules/roles/common/enums";

export const ROLES_FOR_AUTOMATICALLY_ACCOUNT_ACTIVATION = [
  EUserRoleName.SUPER_ADMIN,
  EUserRoleName.LFH_BOOKING_OFFICER,
  EUserRoleName.IND_CLIENT,
  EUserRoleName.IND_PROFESSIONAL_INTERPRETER,
  EUserRoleName.IND_LANGUAGE_BUDDY_INTERPRETER,
  EUserRoleName.CORPORATE_CLIENTS_ADMIN,
  EUserRoleName.CORPORATE_CLIENTS_RECEPTIONIST,
  EUserRoleName.CORPORATE_CLIENTS_IND_USER,
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDERS_ADMIN,
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDERS_RECEPTIONIST,
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDERS_IND_INTERPRETER,
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDER_CORPORATE_CLIENTS_ADMIN,
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDER_CORPORATE_CLIENTS_RECEPTIONIST,
  EUserRoleName.CORPORATE_INTERPRETING_PROVIDER_CORPORATE_CLIENTS_IND_USER,
];
