import { ELanguages } from "src/modules/interpreter-profile/common/enum";

export const ESignLanguages = [
  /**
   ** Naati: Sign Languages
   */

  ELanguages.AUSLAN,
  ELanguages.DEAF_INTERPRETER,
  ELanguages.ADAPTED_SIGN_LANGUAGE_AND_AUSLAN,
  ELanguages.AMERICAN_SIGN_LANGUAGE_AND_AUSLAN,
  ELanguages.BHUTAN_SIGN_LANGUAGE_AND_AUSLAN,
  ELanguages.BRITISH_SIGN_LANGUAGE_AND_AUSLAN,
  ELanguages.INTERNATIONAL_SIGN_LANGUAGE_AND_AUSLAN,
  ELanguages.NEW_ZEALAND_SIGN_LANGUAGE_AND_AUSLAN,
  ELanguages.NON_CONVENTIONAL_SIGN_LANGUAGE_AND_AUSLAN,
  ELanguages.OTHER_CONVENTIONAL_SIGN_LANGUAGE_AND_AUSLAN,
  ELanguages.WRITTEN_ENGLISH_AND_AUSLAN,
  ELanguages.WRITTEN_ENGLISH_AND_NON_CONVENTIONAL_SIGN_LANGUAGE,

  /**
   ** Others: Sign Languages
   */

  ELanguages.AMERICAN_SIGN_LANGUAGE,
  ELanguages.NEW_ZEALAND_SIGN_LANGUAGE,
];
