export enum EChartLine {
  ACTIVE_USERS = "activeUser",
  REGISTERED_USERS = "registeredUser",
  INACTIVE_ACCOUNTS = "inactiveAccount",
  UNSUCCESSFUL_REGISTRATION = "unsuccessfulRegistration",
  NEW_USER_REGISTRATION = "newUserRegistration",
  ACTIVE_INTERPRETERS = "activeInterpreters",
  INTERPRETER_NOT_FOUND = "interpreterNotFound",
  DELETED_ACCOUNTS = "deletedAccounts",
  ACCEPTED_APPOINTMENTS = "acceptedAppointments",
  REJECTED_APPOINTMENTS = "rejectedAppointments",
  CREATED_APPOINTMENTS = "createdAppointments",
  COMPLETED_APPOINTMENTS = "completedAppointments",
  APPOINTMENTS_DURATION = "appointmentsDuration",
  CANCELLED_APPOINTMENTS = "cancelledAppointments",
  UNANSWERED_ON_DEMAND_APPOINTMENTS = "unansweredOnDemandAppointments",
  APPOINTMENTS_WITHOUT_INTERPRETER = "appointmentsWithoutInterpreter",
}
