import { EUserRoleName } from "src/modules/roles/common/enums";

export enum CompanyAdminRole {
  CORPORATE_CLIENTS_SUPER_ADMIN = EUserRoleName.CORPORATE_CLIENTS_SUPER_ADMIN,
  CORPORATE_INTERPRETING_PROVIDER_CORPORATE_CLIENTS_SUPER_ADMIN = EUserRoleName.CORPORATE_INTERPRETING_PROVIDER_CORPORATE_CLIENTS_SUPER_ADMIN,
}
