import {
  NUMBER_OF_MINUTES_IN_DAY,
  NUMBER_OF_MINUTES_IN_FOUR_DAYS,
  NUMBER_OF_MINUTES_IN_HALF_HOUR,
  NUMBER_OF_MINUTES_IN_THREE_DAYS,
  NUMBER_OF_MINUTES_IN_TWELVE_HOURS,
  NUMBER_OF_MINUTES_IN_TWO_DAYS,
} from "src/common/constants";
import { EPaymentStatus } from "src/modules/payments/common/enums";

export const MIN_NUM_DAYS_BEFORE_APPOINTMENT_TO_PAY = 4;
export const MINUTES_BEFORE_START_AS_REASON_TO_CANCEL = 5;
export const PAYMENT_FRAMES = [
  NUMBER_OF_MINUTES_IN_HALF_HOUR,
  NUMBER_OF_MINUTES_IN_TWELVE_HOURS,
  NUMBER_OF_MINUTES_IN_DAY,
  NUMBER_OF_MINUTES_IN_TWO_DAYS,
  NUMBER_OF_MINUTES_IN_THREE_DAYS,
  NUMBER_OF_MINUTES_IN_FOUR_DAYS,
];

export const UNFINISHED_DEPOSIT_CHARGE_STATUSES: EPaymentStatus[] = [
  EPaymentStatus.DEPOSIT_PAYMENT_REQUEST_INITIALIZING,
  EPaymentStatus.DEPOSIT_PAYMENT_REQUEST_CREATING,
  EPaymentStatus.BANK_ACCOUNT_CHARGE_PENDING,
  EPaymentStatus.PAYMENT_REQUEST_CREATED,
  EPaymentStatus.BANK_ACCOUNT_CHARGE_TRANSACTION_CREATED,
  EPaymentStatus.BANK_ACCOUNT_CHARGE_SUCCEEDED,
];
